-- Hive DDL for creating tables on HDFS data

-- Database for raw data
CREATE DATABASE IF NOT EXISTS raw_data
COMMENT 'Raw data landing zone from source systems'
LOCATION '/user/hive/warehouse/raw_data.db';

USE raw_data;

-- Raw Transactions Table
CREATE EXTERNAL TABLE IF NOT EXISTS raw_transactions (
    trans_id STRING COMMENT 'Unique transaction identifier',
    customer_id INT COMMENT 'Customer ID from core banking',
    amount DOUBLE COMMENT 'Transaction amount',
    category STRING COMMENT 'Transaction category (Groceries, Travel, etc.)',
    trans_date STRING COMMENT 'Transaction date YYYY-MM-DD'
)
COMMENT 'Raw transaction logs from ATM/POS/Online banking'
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/data/raw/transactions'
TBLPROPERTIES (
    'creator' = 'ETL_Service',
    'created_date' = '2025-12-27',
    'source_system' = 'Core_Banking_System',
    'retention_days' = '365',
    'classification' = 'Confidential'
);

-- Raw Web Logs Table
CREATE EXTERNAL TABLE IF NOT EXISTS raw_weblogs (
    log_id STRING COMMENT 'Unique log entry ID',
    customer_id INT COMMENT 'Customer ID',
    url_visited STRING COMMENT 'URL path visited',
    timestamp STRING COMMENT 'Timestamp of visit',
    user_agent STRING COMMENT 'Browser user agent',
    session_id STRING COMMENT 'User session ID'
)
COMMENT 'Web and mobile app clickstream data'
STORED AS JSONFILE
LOCATION '/data/raw/weblogs'
TBLPROPERTIES (
    'creator' = 'Web_Analytics_Team',
    'created_date' = '2025-12-27',
    'source_system' = 'Web_Server_Logs',
    'retention_days' = '90',
    'classification' = 'Internal'
);

-- Database for processed data
CREATE DATABASE IF NOT EXISTS processed_data
COMMENT 'Curated and processed datasets'
LOCATION '/user/hive/warehouse/processed_data.db';

USE processed_data;

-- Travel Spending Aggregation
CREATE EXTERNAL TABLE IF NOT EXISTS travel_spend_agg (
    customer_id INT,
    total_travel_spend DOUBLE,
    transaction_count INT,
    avg_transaction_amount DOUBLE,
    last_travel_purchase STRING
)
COMMENT 'Aggregated travel spending per customer - Generated by Spark Job'
PARTITIONED BY (run_date STRING)
STORED AS PARQUET
LOCATION '/data/processed/travel_spend'
TBLPROPERTIES (
    'creator' = 'Spark_Analytics_Job',
    'source_tables' = 'raw_data.raw_transactions',
    'update_frequency' = 'Daily',
    'owner' = 'Data_Science_Team'
);

-- Travel Page Visits
CREATE EXTERNAL TABLE IF NOT EXISTS travel_page_visits (
    customer_id INT,
    travel_page_visits INT,
    first_visit_date STRING,
    last_visit_date STRING
)
COMMENT 'Travel-related web page visits per customer'
PARTITIONED BY (run_date STRING)
STORED AS PARQUET
LOCATION '/data/processed/travel_visits'
TBLPROPERTIES (
    'creator' = 'Spark_Analytics_Job',
    'source_tables' = 'raw_data.raw_weblogs',
    'update_frequency' = 'Daily',
    'owner' = 'Marketing_Team'
);
