-- Initialize PostgreSQL database for Customer Data

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    customer_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    credit_score INT CHECK (credit_score BETWEEN 300 AND 850),
    current_balance DECIMAL(12, 2) DEFAULT 0.00,
    account_opening_date DATE DEFAULT CURRENT_DATE,
    customer_segment VARCHAR(50),
    city VARCHAR(100),
    country VARCHAR(100) DEFAULT 'Sri Lanka',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on commonly queried fields
CREATE INDEX idx_credit_score ON customers(credit_score);
CREATE INDEX idx_customer_segment ON customers(customer_segment);

-- Create promo_eligibility table (output of Spark job)
CREATE TABLE IF NOT EXISTS promo_eligibility (
    id SERIAL PRIMARY KEY,
    customer_id INT NOT NULL,
    promo_code VARCHAR(50) NOT NULL,
    propensity_score FLOAT CHECK (propensity_score BETWEEN 0 AND 1),
    total_travel_spend DECIMAL(12, 2),
    travel_page_visits INT,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    campaign_name VARCHAR(100),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE
);

CREATE INDEX idx_propensity_score ON promo_eligibility(propensity_score DESC);
CREATE INDEX idx_campaign ON promo_eligibility(campaign_name);

-- Create audit table for tracking
CREATE TABLE IF NOT EXISTS pipeline_audit (
    audit_id SERIAL PRIMARY KEY,
    pipeline_name VARCHAR(100),
    run_date DATE,
    status VARCHAR(20),
    records_processed INT,
    execution_time_seconds INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample comment
COMMENT ON TABLE customers IS 'Customer master data from core banking system';
COMMENT ON TABLE promo_eligibility IS 'Target customers for marketing campaigns - generated by Spark propensity model';
COMMENT ON TABLE pipeline_audit IS 'Audit log for all data pipeline executions';
